@ECHO OFF
CLS
SETLOCAL

SET CURRENT_DIR=%~dp0
SET CURRENT_DIR=%CURRENT_DIR:~0,-1%
SET TIMESTAMP=%DATE:~-10%_%TIME%
SET TIMESTAMP=%TIMESTAMP:/=_%
SET TIMESTAMP=%TIMESTAMP::=_%
SET TIMESTAMP=%TIMESTAMP:.=_%
SET TIMESTAMP=%TIMESTAMP: =_%
SET TIMESTAMP=%TIMESTAMP:,=_%

PowerShell -ExecutionPolicy ByPass -File "%CURRENT_DIR%\%~n0.ps1" %*

ENDLOCAL